"use client";

import { useState } from "react";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Eye, ThumbsUp, ThumbsDown, Sparkles, RefreshCw } from "lucide-react";
import { Separator } from "@/components/ui/separator";
import { Volkhov } from "next/font/google";

const volkhov = Volkhov({ weight: ["400", "700"], subsets: ["latin"] });

interface ProductSamplesGridProps {
  productType: string;
  selectedSample: string | null;
  onSelectSample: (sampleId: string) => void;
}

export function ProductSamplesGrid({ productType, selectedSample, onSelectSample }: ProductSamplesGridProps) {
  const [viewMode, setViewMode] = useState<"grid" | "details">("grid");
  const [activeTab, setActiveTab] = useState("all");

  // These would be generated by AI based on the product idea and customization options
  const samples = [
    {
      id: "sample1",
      name: "Eco Runner",
      description: "Minimalist design with recycled materials and breathable mesh panels",
      image: "/placeholder.svg?height=300&width=400&text=Eco+Runner",
      sustainability: "Very High",
      priceEstimate: "$80-100",
      features: ["Recycled PET upper", "Natural rubber sole", "Breathable mesh", "Water resistant"],
      category: "sustainable",
    },
    {
      id: "sample2",
      name: "Urban Trek",
      description: "Modern urban design with premium materials and sleek profile",
      image: "/placeholder.svg?height=300&width=400&text=Urban+Trek",
      sustainability: "Medium",
      priceEstimate: "$120-150",
      features: ["Premium leather accents", "Cushioned insole", "Reinforced heel", "Anti-slip tread"],
      category: "premium",
    },
    {
      id: "sample3",
      name: "Performance Pro",
      description: "High-performance design with technical features for serious athletes",
      image: "/placeholder.svg?height=300&width=400&text=Performance+Pro",
      sustainability: "Medium",
      priceEstimate: "$130-160",
      features: ["Responsive cushioning", "Lightweight construction", "Enhanced stability", "Quick-dry materials"],
      category: "performance",
    },
    {
      id: "sample4",
      name: "Classic Comfort",
      description: "Timeless design focusing on all-day comfort and versatility",
      image: "/placeholder.svg?height=300&width=400&text=Classic+Comfort",
      sustainability: "High",
      priceEstimate: "$70-90",
      features: ["Organic cotton lining", "Memory foam insole", "Flexible outsole", "Wide toe box"],
      category: "casual",
    },
    {
      id: "sample5",
      name: "Trail Blazer",
      description: "Rugged design for outdoor adventures with durable construction",
      image: "/placeholder.svg?height=300&width=400&text=Trail+Blazer",
      sustainability: "High",
      priceEstimate: "$110-140",
      features: ["Water-resistant upper", "Aggressive tread pattern", "Ankle support", "Protective toe cap"],
      category: "performance",
    },
    {
      id: "sample6",
      name: "Fashion Forward",
      description: "Trendy design with unique aesthetic elements and premium finishes",
      image: "/placeholder.svg?height=300&width=400&text=Fashion+Forward",
      sustainability: "Medium",
      priceEstimate: "$140-180",
      features: ["Designer aesthetics", "Premium materials", "Unique color accents", "Custom hardware"],
      category: "premium",
    },
  ];

  const filteredSamples = activeTab === "all" ? samples : samples.filter((sample) => sample.category === activeTab);

  return (
    <div>
      <div className="mb-6">
        <h2 className={`text-2xl font-semibold mb-2 ${volkhov.className}`}>AI-Generated Design Options</h2>
        <p className="text-[#1C1917]">
          Based on your {productType} idea and customization preferences, we've generated these design options. Select
          one to view detailed specifications and request quotes.
        </p>
      </div>

      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6">
        <Tabs defaultValue="all" value={activeTab} onValueChange={setActiveTab} className="w-full md:w-auto">
          <TabsList>
            <TabsTrigger value="all">All Designs</TabsTrigger>
            <TabsTrigger value="sustainable">Sustainable</TabsTrigger>
            <TabsTrigger value="performance">Performance</TabsTrigger>
            <TabsTrigger value="premium">Premium</TabsTrigger>
            <TabsTrigger value="casual">Casual</TabsTrigger>
          </TabsList>
        </Tabs>

        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" className="flex items-center gap-1">
            <RefreshCw className="h-4 w-4" /> Regenerate Options
          </Button>
          <Button
            variant="outline"
            size="sm"
            className="flex items-center gap-1"
            onClick={() => setViewMode(viewMode === "grid" ? "details" : "grid")}
          >
            <Eye className="h-4 w-4" /> {viewMode === "grid" ? "Detailed View" : "Grid View"}
          </Button>
        </div>
      </div>

      {viewMode === "grid" ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredSamples.map((sample) => (
            <Card
              key={sample.id}
              className={`overflow-hidden cursor-pointer transition-all hover:shadow-md ${
                selectedSample === sample.id ? "ring-2 ring-primary" : ""
              }`}
              onClick={() => onSelectSample(sample.id)}
            >
              <div className="aspect-video w-full overflow-hidden bg-muted">
                <img
                  src={sample.image || "/placeholder.svg"}
                  alt={sample.name}
                  className="h-full w-full object-cover"
                />
              </div>
              <CardHeader className="p-4 pb-0">
                <div className="flex justify-between items-start">
                  <CardTitle className={volkhov.className}>{sample.name}</CardTitle>
                  <Badge variant="outline">{sample.sustainability} Sustainability</Badge>
                </div>
                <CardDescription className="line-clamp-2 mt-1">{sample.description}</CardDescription>
              </CardHeader>
              <CardContent className="p-4 pt-2">
                <div className="flex flex-wrap gap-1 mt-2">
                  {sample.features.slice(0, 2).map((feature, index) => (
                    <Badge key={index} variant="secondary" className="text-xs">
                      {feature}
                    </Badge>
                  ))}
                  {sample.features.length > 2 && (
                    <Badge variant="secondary" className="text-xs">
                      +{sample.features.length - 2} more
                    </Badge>
                  )}
                </div>
              </CardContent>
              <CardFooter className="p-4 pt-0 flex justify-between">
                <div className="text-sm font-medium">{sample.priceEstimate}</div>
                <div className="flex gap-2">
                  <Button variant="ghost" size="icon" className="h-8 w-8">
                    <ThumbsUp className="h-4 w-4" />
                  </Button>
                  <Button variant="ghost" size="icon" className="h-8 w-8">
                    <ThumbsDown className="h-4 w-4" />
                  </Button>
                </div>
              </CardFooter>
            </Card>
          ))}
        </div>
      ) : (
        <div className="space-y-6">
          {filteredSamples.map((sample) => (
            <Card
              key={sample.id}
              className={`overflow-hidden cursor-pointer transition-all hover:shadow-md ${
                selectedSample === sample.id ? "ring-2 ring-primary" : ""
              }`}
              onClick={() => onSelectSample(sample.id)}
            >
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div className="md:col-span-1">
                  <div className="h-full w-full overflow-hidden bg-muted">
                    <img
                      src={sample.image || "/placeholder.svg"}
                      alt={sample.name}
                      className="h-full w-full object-cover"
                    />
                  </div>
                </div>
                <div className="md:col-span-2 p-6">
                  <div className="flex justify-between items-start mb-2">
                    <div>
                      <h3 className="text-xl font-semibold">{sample.name}</h3>
                      <p className="text-[#1C1917]">{sample.description}</p>
                    </div>
                    <Badge variant="outline">{sample.sustainability} Sustainability</Badge>
                  </div>

                  <Separator className="my-4" />

                  <div className="grid grid-cols-2 gap-4 mb-4">
                    <div>
                      <h4 className="text-sm font-medium text-[#1C1917] mb-1">Key Features</h4>
                      <ul className="space-y-1">
                        {sample.features.map((feature, index) => (
                          <li key={index} className="text-sm flex items-center gap-2">
                            <Sparkles className="h-3 w-3 text-zinc-900" /> {feature}
                          </li>
                        ))}
                      </ul>
                    </div>
                    <div>
                      <h4 className="text-sm font-medium text-[#1C1917] mb-1">Production Details</h4>
                      <div className="space-y-1 text-sm">
                        <p>Estimated Price: {sample.priceEstimate}</p>
                        <p>Lead Time: 3-4 weeks</p>
                        <p>Min. Order: 100 units</p>
                        <p>Available Sizes: XS-XXL</p>
                      </div>
                    </div>
                  </div>

                  <div className="flex justify-between items-center">
                    <Button
                      variant={selectedSample === sample.id ? "default" : "outline"}
                      onClick={(e) => {
                        e.stopPropagation();
                        onSelectSample(sample.id);
                      }}
                    >
                      {selectedSample === sample.id ? "Selected" : "Select This Design"}
                    </Button>
                    <div className="flex gap-2">
                      <Button variant="ghost" size="sm" className="flex items-center gap-1">
                        <ThumbsUp className="h-4 w-4" /> Like
                      </Button>
                      <Button variant="ghost" size="sm" className="flex items-center gap-1">
                        <ThumbsDown className="h-4 w-4" /> Dislike
                      </Button>
                    </div>
                  </div>
                </div>
              </div>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
