// Industry benchmarks for each section
export const industryBenchmarks = {
  // Original section benchmarks
  "Product Overview":
    "Product descriptions typically include key features, target market, and unique selling points in 50-100 words.",
  Materials:
    "Leading brands in this category typically use materials that balance durability, cost, and sustainability considerations.",
  "Measurements & Tolerance":
    "Standard dimensions for this product type follow ergonomic guidelines and common manufacturing constraints.",
  "Construction Details":
    "Industry standard construction methods prioritize durability, cost efficiency, and aesthetic considerations.",
  "Hardware Components":
    "Hardware selection typically balances functionality, durability, brand identity, and cost considerations.",
  Colors: "Current market trends favor this color palette based on consumer preference data and seasonal forecasts.",
  "Size Range": "This size range covers approximately 95% of the target demographic based on anthropometric data.",
  Packaging: "Industry standard packaging balances protection, presentation, sustainability, and shipping efficiency.",
  "Care Instructions": "Care instructions follow industry standards and legal requirements for textile labeling.",
  "Quality Standards": "Quality standards align with industry benchmarks for similar price point products.",
  "Production Notes":
    "Production notes typically include critical manufacturing considerations and quality control checkpoints.",
  Labels: "The Labeling section is AI-generated by default",
  // New consolidated section benchmarks
  Visual:
    "Visual presentation includes high-quality product images and a cohesive color palette that reflects brand identity.",
  "Factory Specs":
    "Factory specifications provide detailed technical images including base views, component breakdowns, close-ups, and technical sketches.",
  Specifications:
    "Product specifications cover overview, materials, measurements, and size range with industry-standard detail.",
  Construction:
    "Construction section details assembly methods, hardware components, and manufacturing techniques.",
  Production:
    "Production section includes packaging, care instructions, quality standards, and manufacturing notes.",
};

export const sections = [
  "Product Overview",
  "Materials",
  "Measurements & Tolerance",
  "Construction Details",
  "Hardware Components",
  "Colors",
  "Size Range",
  "Labels",
  "Packaging",
  "Care Instructions",
  "Quality Standards",
  "Production Notes",
];

export const sectionKeyMap: Record<string, string> = {
  // Original section mappings
  "Product Visualization": "productVisualization",
  "Product Overview": "productOverview",
  Materials: "materials",
  "Measurements & Tolerance": "dimensions",
  "Construction Details": "constructionDetails",
  "Hardware Components": "hardwareComponents",
  Colors: "colors",
  "Size Range": "sizeRange",
  Labels: "labels",
  Packaging: "packaging",
  "Care Instructions": "careInstructions",
  "Quality Standards": "qualityStandards",
  "Production Notes": "productionNotes",
  // New consolidated section mappings
  Visual: "visual",
  "Factory Specs": "factory-specs",
  Specifications: "specifications",
  Construction: "construction",
  Production: "production",
};
